### ISSUE TITLE
Try to add CPT-4 but failed

### ISSUE THREAD

**Issue by WangNeos** [OHDSI/Vocabulary-v5.0#1085]
[INFO ] 2024-12-18 10:24:44.189 [main] ConceptService - Writing updated data to CONCEPT.csv
[ERROR] 2024-12-18 10:24:44.259 [main] Application - Cannot invoke "java.lang.Integer.intValue()" because "this.conceptIdIndex" is null
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "this.conceptIdIndex" is null
	at org.odhsi.utils.cpt.domain.Concept.getConceptId(Concept.java:60) ~[cpt4.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:727) ~[?:?]
	at org.odhsi.utils.cpt.repository.ConceptRepository.filterAlreadyPresentInFileConcepts(ConceptRepository.java:86) ~[cpt4.jar:?]
	at org.odhsi.utils.cpt.services.ConceptService.process(ConceptService.java:34) ~[cpt4.jar:?]
	at org.odhsi.utils.cpt.Application.main(Application.java:40) [cpt4.jar:?]

**Comment by m-khitrun** [comment]
Hello, @WangNeos! 
Sorry for the delayed reply. Does your problem still persist?

**Comment by TinyRickC137** [comment]
Closing this issue as outdated. It is highly likely the vocabularies have not caused it. 
Please feel free to reopen the issue if needed.
